[package]
name = "stark_test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.213"
serde_json = "1.0.132"
winter-air = "0.10.1"
winter-fri = "0.10.1"
winter-utils = "0.10.1"
winterfell = "0.10.1"
